// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type FinanceCreditCard struct {
	BankName   string         `json:"bank_name"`
	CardName   string         `json:"card_name"`
	CardNumber string         `json:"card_number"`
	Cvv        string         `json:"cvv"`
	Pin        string         `json:"pin"`
	Usage      sql.NullString `json:"usage"`
	UserID     int32          `json:"user_id"`
}

type FinanceSalarySplitItems struct {
	ID            int32          `json:"id"`
	SplitID       int32          `json:"split_id"`
	CategoryName  string         `json:"category_name"`
	Amount        string         `json:"amount"`
	MoveTo        sql.NullString `json:"move_to"`
	IsTransferred sql.NullBool   `json:"is_transferred"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type FinanceSalarySplits struct {
	ID                 int32          `json:"id"`
	UserID             int32          `json:"user_id"`
	Month              time.Time      `json:"month"`
	TotalSalary        string         `json:"total_salary"`
	Notes              sql.NullString `json:"notes"`
	IsFullyTransferred sql.NullBool   `json:"is_fully_transferred"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}
