// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "Finance"."users" (
    email,
    user_password,
    username
) VALUES (
  $1, $2, $3
)
RETURNING id, email, username, user_password, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	UserPassword string `json:"user_password"`
	Username     string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (FinanceUsers, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.UserPassword, arg.Username)
	var i FinanceUsers
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.UserPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM "Finance"."users"
WHERE email = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByEmail, email)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, user_password, created_at, updated_at FROM "Finance"."users"
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (FinanceUsers, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i FinanceUsers
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.UserPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, username, user_password, created_at, updated_at FROM "Finance"."users"
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (FinanceUsers, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i FinanceUsers
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.UserPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, user_password, created_at, updated_at FROM "Finance"."users"
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (FinanceUsers, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i FinanceUsers
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.UserPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
